### PR TITLE
Syntax Error in Listing 2.018.sql

### PR DESCRIPTION
**Pull request by richardbroersma**
The create function statement needed to be terminated with a semicolon.  Also, I rearrange the "LANGUAGE plpgsql" statement to match the convention shown in https://www.postgresql.org/docs/9.6/static/plpgsql-trigger.html

With this change the SQL file executes without any errors.

### CODE REVIEW

**Comment by bclothier** [comment]
Thanks for pointing this out –

 

I want to note, though that the LANGUAGE in the top, rather than bottom is primarily for ANSI compliance as noted in PostgreSQL documentation. 

 

https://www.postgresql.org/docs/9.5/static/sql-createfunction.html

 

“attribute

The historical way to specify optional pieces of information about the function.”

 

I did not have to terminate the function itself since I was using heredoc delimiters and it compiled. I will double-check this. Thanks again!

 

Ben

**Comment by bclothier** [comment]
Just to follow up on this – I tried it again in pgAdminIII and I could execute with or without a terminating semi-colon.

 

Nonetheless, I will add it so it’s more consistent with everything else.

 

As for the LANGUAGE, I thought I had saw PostgreSQL documentation that says that the LANGUAGE on top should be used for ANSI compliance but I can’t find that specific statement I had in mind and I see that I quoted the wrong part earlier. 

 

From: "bgclothier@gmail.com" <bgclothier@gmail.com>
Date: Tuesday, June 14, 2016 at 12:57 PM
To: TexanInParis/Effective-SQL <reply@reply.github.com>, TexanInParis/Effective-SQL <Effective-SQL@noreply.github.com>
Subject: Re: [TexanInParis/Effective-SQL] Syntax Error in Listing 2.018.sql (#8)

 

Thanks for pointing this out –

 

I want to note, though that the LANGUAGE in the top, rather than bottom is primarily for ANSI compliance as noted in PostgreSQL documentation. 

 

https://www.postgresql.org/docs/9.5/static/sql-createfunction.html

 

“attribute

The historical way to specify optional pieces of information about the function.”

 

I did not have to terminate the function itself since I was using heredoc delimiters and it compiled. I will double-check this. Thanks again!

 

Ben

**Comment by bclothier** [comment]
Found the note. I was looking in wrong place - it was under the Compatibility section on the bottom of the page linked prior:

"A CREATE FUNCTION command is defined in SQL:1999 and later. The PostgreSQL version is similar but not fully compatible. The attributes are not portable, neither are the different available languages.

For compatibility with some other database systems, argmode can be written either before or after argname. But only the first way is standard-compliant."

Let me know what you think.

**Comment by richardbroersma** [comment]
Actually looking at synopsis of
https://www.postgresql.org/docs/9.6/static/sql-createfunction.html. I see
the function definition is defined to come after language attribute.  So I
guess it is better to keep it the way it is.

On Tuesday, June 14, 2016, bclothier <notifications@github.com> wrote:

> Found the note. I was looking in wrong place - it was under the
> Compatibility section on the bottom of the page linked prior:
>
> "A CREATE FUNCTION command is defined in SQL:1999 and later. The
> PostgreSQL version is similar but not fully compatible. The attributes are
> not portable, neither are the different available languages.
>
> For compatibility with some other database systems, argmode can be written
> either before or after argname. But only the first way is
> standard-compliant."
>
> Let me know what you think.
>
>
> > On Jun 14, 2016, at 6:33 PM, Ben Clothier <bgclothier@gmail.com
> <javascript:_e(%7B%7D,'cvml','bgclothier@gmail.com');>> wrote:
> >
> > Just to follow up on this – I tried it again in pgAdminIII and I could
> execute with or without a terminating semi-colon.
> >
> > Nonetheless, I will add it so it’s more consistent with everything else.
> >
> > As for the LANGUAGE, I thought I had saw PostgreSQL documentation that
> says that the LANGUAGE on top should be used for ANSI compliance but I
> can’t find that specific statement I had in mind and I see that I quoted
> the wrong part earlier.
> >
> > From: "bgclothier@gmail.com
> <javascript:_e(%7B%7D,'cvml','bgclothier@gmail.com');>" <
> bgclothier@gmail.com
> <javascript:_e(%7B%7D,'cvml','bgclothier@gmail.com');>>
> > Date: Tuesday, June 14, 2016 at 12:57 PM
> > To: TexanInParis/Effective-SQL <reply@reply.github.com
> <javascript:_e(%7B%7D,'cvml','reply@reply.github.com');>>,
> TexanInParis/Effective-SQL <Effective-SQL@noreply.github.com
> <javascript:_e(%7B%7D,'cvml','Effective-SQL@noreply.github.com');>>
> > Subject: Re: [TexanInParis/Effective-SQL] Syntax Error in Listing
> 2.018.sql (#8)
> >
> > Thanks for pointing this out –
> >
> > I want to note, though that the LANGUAGE in the top, rather than bottom
> is primarily for ANSI compliance as noted in PostgreSQL documentation.
> >
> > https://www.postgresql.org/docs/9.5/static/sql-createfunction.html
> >
> > “attribute
> > The historical way to specify optional pieces of information about the
> function.”
> >
> > I did not have to terminate the function itself since I was using
> heredoc delimiters and it compiled. I will double-check this. Thanks again!
> >
> > Ben
> >
> > From: richardbroersma <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > Reply-To: TexanInParis/Effective-SQL <reply@reply.github.com
> <javascript:_e(%7B%7D,'cvml','reply@reply.github.com');>>
> > Date: Tuesday, June 14, 2016 at 12:40 PM
> > To: TexanInParis/Effective-SQL <Effective-SQL@noreply.github.com
> <javascript:_e(%7B%7D,'cvml','Effective-SQL@noreply.github.com');>>
> > Subject: [TexanInParis/Effective-SQL] Syntax Error in Listing 2.018.sql
> (#8)
> >
> > The create function statement needed to be terminated with a semicolon.
> Also, I rearrange the "LANGUAGE plpgsql" statement to match the convention
> shown in https://www.postgresql.org/docs/9.6/static/plpgsql-trigger.html
> >
> > With this change the SQL file executes without any errors.
> >
> > You can view, comment on, or merge this pull request online at:
> >
> > https://github.com/TexanInParis/Effective-SQL/pull/8
> >
> > Commit Summary
> >
> > Syntax Error in Listing 2.018.sql
> > File Changes
> >
> > M PostgreSQL/Chapter 02/Listing 2.018.sql (7)
> > Patch Links:
> >
> > https://github.com/TexanInParis/Effective-SQL/pull/8.patch
> > https://github.com/TexanInParis/Effective-SQL/pull/8.diff
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub, or mute the thread.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/TexanInParis/Effective-SQL/pull/8#issuecomment-226066768>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEHQ78CMIgI-CsoiaP5FY1vn73MlqkQdks5qL1nmgaJpZM4I1kzU>
> .
>


-- 
Regards,
Richard Broersma Jr.

**Comment by bclothier** [comment]
Addressed with this commit: https://github.com/TexanInParis/Effective-SQL/commit/9ba8fe4f95b951d16e0b43e621a0a6042a78dcb1

(left the language but added the semicolon)

Thanks!

**Pull request closed without merging**
